import * as React from "react";
import { ChartContainer, ChartTooltip, ChartTooltipContent } from "../../ui/chart";
import { Area, AreaChart, CartesianGrid, XAxis, YAxis } from "recharts";
import type { StatsDataPoint } from "~/apis";

export function HistoricalCharts({ historyData }: { historyData: Record<string, StatsDataPoint[]> }) {
  const backendIds = Object.keys(historyData);

  // Generate colors for each backend using CSS variables
  // Use var(...) so they resolve to actual theme colors
  const colorKeys = [
    "var(--chart-1)",
    "var(--chart-2)",
    "var(--chart-3)",
    "var(--chart-4)",
    "var(--chart-5)"
  ];

  // Prepare data for charts - merge all backends into single timeline
  const mergedData = React.useMemo(() => {
    const timeMap = new Map<string, any>();

    backendIds.forEach((backendId) => {
      const points = historyData[backendId] || [];
      points.forEach(point => {
        const time = new Date(point.timestamp).getTime();
        const timeKey = time.toString();

        if (!timeMap.has(timeKey)) {
          timeMap.set(timeKey, { time, timestamp: point.timestamp });
        }

        const entry = timeMap.get(timeKey);
        entry[`successRate_${backendId}`] = point.successRate * 100;
        entry[`streamingTtft_${backendId}`] = point.averageStreamingTTFT || 0;
        entry[`nonStreamingTtft_${backendId}`] = point.averageNonStreamingTTFT || 0;
        entry[`requests_${backendId}`] = point.totalRequests;
      });
    });

    return Array.from(timeMap.values()).sort((a, b) => a.time - b.time);
  }, [historyData, backendIds]);

  const formatTime = (timestamp: string | Date) => {
    const date = new Date(timestamp);
    return date.toLocaleTimeString('zh-CN', { hour: '2-digit', minute: '2-digit' });
  };

  const chartConfig = React.useMemo(() => {
    const config: Record<string, { label: string; color: string }> = {};
    backendIds.forEach((id) => {
      const blue = "var(--chart-2)"; // unified blue from theme palette
      config[`successRate_${id}`] = {
        label: id,
        color: blue,
      };
      config[`streamingTtft_${id}`] = {
        label: `${id} (Streaming)`,
        color: blue,
      };
      config[`nonStreamingTtft_${id}`] = {
        label: `${id} (Non-Streaming)`,
        color: blue,
      };
      config[`requests_${id}`] = {
        label: id,
        color: blue,
      };
    });
    return config;
  }, [backendIds]);

  return (
    <>
      {/* Success Rate Chart */}
      <div>
        <div className="mb-4">
          <h3 className="text-base font-medium mb-1">成功率趋势</h3>
          <p className="text-sm text-muted-foreground">各 Backend 请求成功率变化 (%)</p>
        </div>
        <ChartContainer config={chartConfig} className="h-[300px] w-full">
          <AreaChart
            accessibilityLayer
            data={mergedData}
            margin={{
              left: 12,
              right: 12,
              top: 12,
            }}
          >
            <CartesianGrid vertical={false} />
            <XAxis
              dataKey="timestamp"
              tickLine={false}
              axisLine={false}
              tickMargin={8}
              tickFormatter={formatTime}
            />
            <YAxis
              domain={[0, 100]}
              tickLine={false}
              axisLine={false}
              tickMargin={8}
              tickFormatter={(value) => `${value}%`}
            />
            <ChartTooltip
              cursor={false}
              content={<ChartTooltipContent indicator="dot" />}
            />
            {backendIds.map((id, index) => (
              <Area
                key={id}
                dataKey={`successRate_${id}`}
                type="linear"
                // Use the per-series CSS variable generated by ChartContainer
                fill={`var(--color-successRate_${id})`}
                fillOpacity={0.25}
                stroke={`var(--color-successRate_${id})`}
                strokeWidth={2}
                stackId="a"
              />
            ))}
          </AreaChart>
        </ChartContainer>
      </div>

      {/* Streaming vs Non-Streaming TTFT Chart */}
      <div>
        <div className="mb-4">
          <h3 className="text-base font-medium mb-1">流式 vs 非流式 TTFT 对比</h3>
          <p className="text-sm text-muted-foreground">分别显示流式请求和非流式请求的首 Token 响应时间 (毫秒)</p>
        </div>
        <ChartContainer config={chartConfig} className="h-[300px] w-full">
          <AreaChart
            accessibilityLayer
            data={mergedData}
            margin={{
              left: 12,
              right: 12,
              top: 12,
            }}
          >
            <CartesianGrid vertical={false} />
            <XAxis
              dataKey="timestamp"
              tickLine={false}
              axisLine={false}
              tickMargin={8}
              tickFormatter={formatTime}
            />
            <YAxis
              tickLine={false}
              axisLine={false}
              tickMargin={8}
              tickFormatter={(value) => `${value}ms`}
            />
            <ChartTooltip
              cursor={false}
              content={<ChartTooltipContent indicator="dot" />}
            />
            {backendIds.map((id) => (
              <Area key={`streaming_${id}`}
                dataKey={`streamingTtft_${id}`}
                type="linear"
                fill={`var(--color-streamingTtft_${id})`}
                fillOpacity={0.15}
                stroke={`var(--color-streamingTtft_${id})`}
                strokeWidth={2}
              />
            ))}
            {backendIds.map((id) => (
              <Area key={`nonStreaming_${id}`}
                dataKey={`nonStreamingTtft_${id}`}
                type="linear"
                fill={`var(--color-nonStreamingTtft_${id})`}
                fillOpacity={0.15}
                stroke={`var(--color-nonStreamingTtft_${id})`}
                strokeWidth={2}
              />
            ))}
          </AreaChart>
        </ChartContainer>
      </div>

      {/* Total Requests Chart */}
      <div>
        <div className="mb-4">
          <h3 className="text-base font-medium mb-1">累计请求数趋势</h3>
          <p className="text-sm text-muted-foreground">各 Backend 处理的总请求数量</p>
        </div>
        <ChartContainer config={chartConfig} className="h-[300px] w-full">
          <AreaChart
            accessibilityLayer
            data={mergedData}
            margin={{
              left: 12,
              right: 12,
              top: 12,
            }}
          >
            <CartesianGrid vertical={false} />
            <XAxis
              dataKey="timestamp"
              tickLine={false}
              axisLine={false}
              tickMargin={8}
              tickFormatter={formatTime}
            />
            <YAxis
              tickLine={false}
              axisLine={false}
              tickMargin={8}
            />
            <ChartTooltip
              cursor={false}
              content={<ChartTooltipContent indicator="dot" />}
            />
            {backendIds.map((id, index) => (
              <Area
                key={id}
                dataKey={`requests_${id}`}
                type="linear"
                fill={`var(--color-requests_${id})`}
                fillOpacity={0.25}
                stroke={`var(--color-requests_${id})`}
                strokeWidth={2}
                stackId="a"
              />
            ))}
          </AreaChart>
        </ChartContainer>
      </div>
    </>
  );
}
